### ISSUE TITLE
SummaryWriter

### ISSUE THREAD

**Issue by zhaojianwen** [Samurais/DeepQA2#3]
using tensorflow1.0, python3.52 to train the model, it looks like there are a bunch of errors.
![image](https://cloud.githubusercontent.com/assets/24785606/24082189/6388b9b2-0c8f-11e7-9ca8-10f691068f1e.png)

**Comment by hzylmf** [comment]
you should change the version of tensorflow, or modify the way of calling

**Comment by angryBird2014** [comment]
sorry,I'm not familiar with the django and when I train the model,and then use 'python manage runserver 0.0.0.0:8000'.but i don't know how to access the web page,can you give me some suggestions?
'

**Comment by Samurais** [comment]
As the sourcecode is tested against tf rc0.11, so it is out of date.
