### ISSUE TITLE
how to access the web interface

### ISSUE THREAD

**Issue by angryBird2014** [Samurais/DeepQA2#6]
It's a 
I'm not familiar with the django and when I train the model,and then use 'python manage runserver 0.0.0.0:8000'.but i don't know how to access the web page,can you give me some suggestions?

**Comment by hohosyk** [comment]
I'd like to add more. I went to http://127.0.0.1:8000/admin/, then there was log in view, but I could not find Username, and Password at db.sqlite3. Would you able to give me advice for log in information?

**Comment by hohosyk** [comment]
I'd like to add more. I went to http://127.0.0.1:8000/admin/, then there was log in view, but I could not find Username, and Password at db.sqlite3. Would you able to give me advice for log in information?

**Comment by hohomango** [comment]
I'd like to add more. I went to http://127.0.0.1:8000/admin/, then there was log in view, but I could not find Username, and Password at db.sqlite3. Would you able to give me advice for log in information?

**Comment by hohomango** [comment]
I went to http://127.0.0.1:8000/api/v1/question

but, have error message as below:
I'd like to know the source at "django\contrib\admin\templates\rest_framework\api.html"

<error message>
TemplateDoesNotExist at /api/v1/question
rest_framework/api.html


Request Method:
GET 

Request URL:
http://127.0.0.1:8000/api/v1/question 

Django Version:
1.10.5 

Exception Type:
TemplateDoesNotExist 

Exception Value:
rest_framework/api.html
 

Exception Location:
C:\Users\Younghwa\Anaconda3\lib\site-packages\django\template\loader.py in get_template, line 25 

Python Executable:
C:\Users\Younghwa\Anaconda3\python.exe 

Python Version:
3.5.2 

Python Path:
['C:\\Users\\Younghwa\\Downloads\\DeepQA2-master\\DeepQA2-master\\save\\deeplearning.cobra.HOME.20170410.030102\\deepqa2\\serve',
 'C:\\Users\\Younghwa\\Downloads\\DeepQA2-master',
 'C:\\Users\\Younghwa\\Anaconda3\\python35.zip',
 'C:\\Users\\Younghwa\\Anaconda3\\DLLs',
 'C:\\Users\\Younghwa\\Anaconda3\\lib',
 'C:\\Users\\Younghwa\\Anaconda3',
 'C:\\Users\\Younghwa\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Younghwa\\Anaconda3\\lib\\site-packages\\Sphinx-1.4.6-py3.5.egg',
 'C:\\Users\\Younghwa\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Younghwa\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Younghwa\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Younghwa\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.5.egg',
 'C:\\Users\\Younghwa\\Downloads\\DeepQA2-master\\DeepQA2-master\\save\\deeplearning.cobra.HOME.20170410.030102\\deepqa2',
 'C:\\Users\\Younghwa\\Downloads\\DeepQA2-master\\DeepQA2-master\\save\\deeplearning.cobra.HOME.20170410.030102\\deepqa2\\utils\\..',
 'C:\\Users\\Younghwa\\Downloads\\DeepQA2-master\\DeepQA2-master\\save\\deeplearning.cobra.HOME.20170410.030102\\deepqa2',
 'C:\\Users\\Younghwa\\Downloads\\DeepQA2-master\\DeepQA2-master\\save\\deeplearning.cobra.HOME.20170410.030102\\deepqa2',
 'C:\\Users\\Younghwa\\Downloads\\DeepQA2-master\\DeepQA2-master\\save\\deeplearning.cobra.HOME.20170410.030102\\deepqa2',
 'C:\\Users\\Younghwa\\Downloads\\DeepQA2-master\\DeepQA2-master\\save\\deeplearning.cobra.HOME.20170410.030102\\deepqa2\\models\\..']
 

Server time:
Tue, 18 Apr 2017 22:10:34 +0000 

Template-loader postmortem

Django tried loading these templates, in this order:

Using engine django:
•django.template.loaders.app_directories.Loader: C:\Users\Younghwa\Anaconda3\lib\site-packages\django\contrib\admin\templates\rest_framework\api.html (Source does not exist)
•django.template.loaders.app_directories.Loader: C:\Users\Younghwa\Anaconda3\lib\site-packages\django\contrib\auth\templates\rest_framework\api.html (Source does not exist)

**Comment by Samurais** [comment]
As it is an api, so I would suggest some tool like Postman.
![image](https://cloud.githubusercontent.com/assets/3538629/25989523/1183e1c6-372f-11e7-9592-2d8b202d8f23.png)

```
POST /api/v1/question HTTP/1.1
Host: 127.0.0.1:8000

Headers:
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQxMjM=

BODY:
{"message": "hello"}
```
