### ISSUE TITLE
中文语料训练之后的问题

### ISSUE THREAD

**Issue by iceray** [Samurais/DeepQA2#7]
您好：
   请问，使用deep2里面提供的中文语料进行训练之后，对于完全按照语料的问题来提问的时候，但是一旦删减几个无关的字并且不影响原语句语义的时候，回答就牛头不对马嘴了，是模型训练的方式导致的吗？还是说是分词导致的？
例如，提问
白鹭如何快速随机出几个不同的数
回答是
百度上例子多  
上面这个是对的，但是，改成下面的提问

如何快速随机出几个不同的数
回答就变成了
请google或者百度 网页嵌入百度地图 变化
上面这个回答，就完全不对了

**Comment by Samurais** [comment]
白鹭时代的语料是我手工整理的，量小。现在我还没有找到质量好的公开的中文对话语料。
