### ISSUE TITLE
在train with docker

### ISSUE THREAD

**Issue by Leechen2014** [Samurais/DeepQA2#8]
按照readME的步骤:
docker pull samurais/deepqa2:latest
cd DeepQA2
执行   ./scripts/train_with_docker.sh 
提示  Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by Leechen2014** [comment]
大致流程我明白了: 应该是先git clone到本地, 然后在切换到本地的DeepQA2 目录先,  最后执行本地的脚本;该脚本需要使用docker以及NVIDIA docker ;

**Comment by Samurais** [comment]
对，docker要运行。
